name: flutter_webview_hook_sample
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_inappwebview: ^6.0.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  freezed_annotation: ^2.4.1
  go_router: ^12.1.3
  hooks_riverpod: ^2.4.9
  intl: ^0.18.1
  logger: ^2.0.2+1
  package_info_plus: ^5.0.1
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  state_notifier: ^1.0.0
  url_launcher: ^6.2.4

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true

  generate: true
