name: Test

env:
  FLUTTER_VERSION: 3.16.9

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: flutter pub get
        run: |
          flutter pub get

      - name: dart format
        run: |
          dart format -o none --set-exit-if-changed $(find ./lib ./test -name "*.dart" -not \( -name "*.freezed.dart" -o -name "*.g.dart" -o -name "*.gen.dart" -o -name "*.gr.dart" -o -name "*.mock.dart" \) )

      - name: flutter analyze
        run: |
          flutter analyze

      - name: flutter test
        run: |
          flutter test --coverage

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Report code coverage
        run: |
          lcov --list coverage/lcov.info --list-full-path --rc lcov_branch_coverage=1
